spring:
  application:
    name: robot-delivery-system

  datasource:
    url: jdbc:h2:mem:robotdb  # Changed from MySQL to H2
    username: root
    password: 'Testing123'
    driver-class-name: org.h2.Driver  # Changed from MySQL to H2


  jpa:
    hibernate:
      ddl-auto: create-drop  # Changed from update to create-drop for H2
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect  # Changed from MySQL8Dialect to H2Dialect
        format_sql: true

  h2:
    console:
      enabled: true
      path: /h2-console

server:
  port: 8080
  servlet:
    context-path: /api

logging:
  level:
    com.robotdelivery: INFO 